FROM ubuntu:20.04 as build

WORKDIR /tmp

#
# install Slurm/MySQL/NFS/cluster scripts

# 1. prereqs from apt
RUN apt-get update && \
DEBIAN_FRONTEND=noninteractive \
apt-get -y install --no-install-recommends tzdata && \
apt-get -y install build-essential vim git python3-pip \
  nfs-common portmap libmariadb-dev mariadb-client mariadb-server \
  munge libmunge-dev libhwloc-dev cgroup-tools libreadline-dev ssed wget sudo curl

# 2. convenient symlinks; NFS mount folder
RUN ln -s /usr/bin/python3 /usr/bin/python && \
mkdir -p /mnt/nfs

# 3. build Slurm
RUN wget https://download.schedmd.com/slurm/slurm-20.11.7.tar.bz2 && \
tar xjf slurm-20.11.7.tar.bz2 && \
cd slurm-20.11.7 && \
./configure --prefix=/usr/local --sysconfdir=/usr/local/etc \
  --with-mysql_config=/usr/bin --with-hdf5=no && \
make && make install

# 4. make Slurm directories
RUN adduser -u 1337 --gecos "" --disabled-password slurm && \
mkdir -p /var/spool/slurm && chown slurm:slurm /var/spool/slurm && \
mkdir -p /run/munge

# 5. configure MySQL
RUN mkdir -p /var/run/mysqld && chown mysql:mysql /var/run/mysqld && \
(mysqld & while ! mysqladmin -s status; do sleep 1; done ) && \
mysql -u root -e "create user 'slurm'@'localhost'" && \
mysql -u root -e "grant all on slurm_acct_db.* TO 'slurm'@'localhost';"

# 6. set up munge
RUN dd if=/dev/zero bs=1 count=1024 of=/etc/munge/munge.key

# 7. Python prereqs
RUN pip3 install pandas crcmod

# 8. install gcloud
RUN mkdir /gcsdk && \
wget -O gcs.tgz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-318.0.0-linux-x86_64.tar.gz && \
tar xzf gcs.tgz -C /gcsdk && \
/gcsdk/google-cloud-sdk/install.sh --usage-reporting false --path-update true --quiet && \
ln -s /gcsdk/google-cloud-sdk/bin/* /usr/bin

# 9. get cluster utility scripts (TODO: better moving Dockerfile_base to parent directory??)
COPY ./src/ /usr/local/share/slurm_gcp_docker/src/
COPY ./conf/ /usr/local/share/slurm_gcp_docker/conf/

# 10. podman
RUN apt-get -qq -y install gnupg && \
. /etc/os-release && \
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | apt-key add - && \
echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list && \
apt-get -qq update && \
apt-get -qq -y install fuse-overlayfs podman iptables && \
DEBIAN_FRONTEND=noninteractive \
apt-get -qq -y install --no-install-recommends tzdata

COPY src/podman_conf/* /etc/containers/

# 11. sudo for all
RUN echo "ALL ALL=(ALL) NOPASSWD: ALL" >>/etc/sudoers

# 12. docker for all (NOTE: we have moved to podman so nested docker or sharing docker daemon is no long required)
# RUN chmod 666 /var/run/docker.sock

#
# clean up /tmp
RUN rm -rf *

#
# clean up packages
RUN apt-get -y remove build-essential vim git && apt-get -y autoremove

#
# set entrypoint
ENTRYPOINT /usr/local/share/slurm_gcp_docker/src/docker_entrypoint_controller.sh

#
# set Slurm environment
ENV SLURM_CONF "/mnt/nfs/clust_conf/slurm/slurm.conf"

#
# update PATH environment
ENV PATH="/usr/local/share/slurm_gcp_docker/src/docker_bin:${PATH}"
